salary = int(input("Укажите вашу заработную плату в месяц: "))
hypothec_percent = int(input("Укажите, какой процент(%) уходит на ипотеку: "))
life_percent = int(input("Укажите, какой процент(%) уходит на жизнь: "))
time_period = int(input("За сколько месяцев нужно рассчитать: "))
hypothec_money = int((salary * hypothec_percent / 100) * time_period)
life_money = int((salary * life_percent / 100) * time_period)
saved_money = int(salary * time_period - (hypothec_money + life_money))
print("На ипотеку было потрачено: ", hypothec_money, " рублей")
print("На жизнь было потрачено: ", life_money, " рублей")
print("Было накоплено: ", saved_money, " рублей")